name: VueExampleFreeCodeCamp
services:
- build_command: npm build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: cempaydas/VueExampleFreeCodeCamp
  name: VueExampleFreeCodeCamp